version: '3.2'
services:
  gitserver:
    build:
      context: ../.
      dockerfile: Dockerfile
    command:
      - '-init'
      - '-start'
    volumes:
      - './initial:/var/lib/initial:ro'
    ports:
      - '8080:80'
