- hosts: localhost
  vars:
    target_dir: /tmp/git-repo
    cleanup: true
    git_backend_port_http: 3333
  tasks:
  - name: "remove Git Repos basedir at {{target_dir}} if  exist"
    file:
      path: "{{target_dir}}"
      state: absent
    when: cleanup

  - name: "Create Git Repos basedir at {{target_dir}} if not exist"
    file:
      path: "{{target_dir}}"
      state: directory


  - name: build the docker buildcontainer
    docker_image:
      name: githttpbackend
      state: present
      path: "{{playbook_dir}}"
      force: yes
    register: buildresult

  - debug: var=buildresult


  - name: create spring boot docker containers
    docker_container:
      name: testGitHttpBackend
      image: githttpbackend
      state: started
      recreate: yes
      command:
        - "-init"
      volumes:
        - "{{playbook_dir}}/example/initial:/var/lib/initial:ro"
      published_ports:
        - "{{git_backend_port_http}}:80"
    register: buildresult

  - debug: var=buildresult


  - name: wait till influx db is started
    uri:
      url: "http://localhost:{{git_backend_port_http}}/ping"
      method: GET
    register: result
    until: result.status == 200
    retries: 5
    delay: 10

  - debug: msg="{}{target_dir}}/myrepo"

  - name: "checkout needet projects from github"
    git:
      repo: "http://localhost:{{git_backend_port_http}}/myrepo.git"
      dest: "{{target_dir}}/myrepo"


  - name: Check that the somefile.conf exists
    stat:
      path: "{{target_dir}}/myrepo/myfile.txt"
    register: stat_result

  - debug: var=stat_result.stat

  - name: insert/update "Match User" configuration block in /etc/ssh/sshd_config
    blockinfile:
      path: "{{target_dir}}/myrepo/myfile.txt"
      block: |
        simple test

  - name: add changes
    command: git add .
    args:
      chdir: "{{target_dir}}/myrepo"

  - name: commit
    command: git commit -m "test commit"
    args:
      chdir: "{{target_dir}}/myrepo"

  - name: push
    command: git push origin master
    args:
      chdir: "{{target_dir}}/myrepo"

#  - name: create spring boot docker containers
#    docker_container:
#      name: testGitHttpBackend
#      image: githttpbackend
#      state: absent
